### PR TITLE
Add ability to hide topic instead of content.

### PR DESCRIPTION
**Pull request by elliott-king**
Tried to keep as simple as possible, I think I hit all of the requirements for your surrounding tools.

Changed only one unit test, otherwise tested simply with:
 `python3 -mflashcards ../examples/example.yaml -I`

Tox hiccups:

* ~~'check' fails because setup.py:31 is too long (Not an addition I made)~~
* I have no interpreter for python3.3, python3.4, python 3.5
* 'report' fails: `coverage combine --append` returns `No data to combine`
   * Not sure what this is about, `coverage report` works just fine.

### CODE REVIEW

**Comment by woile** [comment]
Thanks a lot, I'll try it later today

**Comment by woile** [comment]
Hey looks good, can you rebase on top of `master`?

**Comment by woile** [comment]
thank you!! :tada:

**Comment by woile** [comment]
`v.0.3.0` released! :100:

**Comment by elliott-king** [comment]
Thanks for making the process so smooth for me.

**Pull request merged**
